mel_spectrogram:
  sample_rate: 16000
  n_fft: 2048
  win_length: 2048
  hop_length: 512
  f_min: 30
  f_max: 8000
  n_mels: 229
  power: 1
  norm: slaney
midi:
  min_pitch: 21
  max_pitch: 108
dataset:
  dataset_dir: maetsro-v3.0.0
  segment_seconds: 20
training:
  mode: note
  accelerator: gpu
  devices: "0"
  precision: 32
  batch_size: 32
  num_workers: 4
  learning_rate: 0.0001
  max_epochs: 100
  optimizer: adam
  output_dir: output
  logger: tensorboard
  logger_name: default
  logger_project: piano-transcription-research
model:
  model_complexity: 48